version: "3.7"

services:
  php:
    image: "php"
    build:
      context: ./docker
    restart: always
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./docker/config/vhosts:/etc/apache2/sites-enabled
      - ./docker/config/dir/dir.conf:/etc/apache2/mods-enabled/dir.conf
      - ./:/var/www/html
    networks:
      - app-network
  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network
  rabbitmq:
    restart: always
    image: rabbitmq:3.9.5
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

volumes:
  postgre:
    driver: local

networks:
  app-network:
    driver: bridge